### ISSUE TITLE
"OSError: could not get source code" - caused by class?

### ISSUE THREAD

**Issue by duichwer** [pawamoy/pytkdocs#15]
Hi,
I am unable to build docs for one file.
If I understand those errors correct than they might be caused by the following class definition:
```python
class GSS(NamedTuple):
    """
        Helper Class to specify the return type of gss
    """

    gss: float
    nA: float
    nB: float
    nAB: float
```
Is there any way to solve this?

```bash
poetry run mkdocs build
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /mnt/c/Users/demo/Documents/repos/myownpackage/site 
Traceback (most recent call last):
  File "/mnt/c/Users/demo/Documents/repos/myownpackage/.venv/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/mnt/c/Users/demo/Documents/repos/myownpackage/.venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/c/Users/demo/Documents/repos/myownpackage/.venv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/mnt/c/Users/demo/Documents/repos/myownpackage/.venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/c/Users/demo/Documents/repos/myownpackage/.venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/c/Users/demo/Documents/repos/myownpackage/.venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/mnt/c/Users/demo/Documents/repos/myownpackage/.venv/lib/python3.6/site-packages/mkdocs/__main__.py", line 163, in build_command
    ), dirty=not clean)
  File "/mnt/c/Users/demo/Documents/repos/myownpackage/.venv/lib/python3.6/site-packages/mkdocs/commands/build.py", line 270, in build
    nav = config['plugins'].run_event('nav', nav, config=config, files=files)
  File "/mnt/c/Users/demo/Documents/repos/myownpackage/.venv/lib/python3.6/site-packages/mkdocs/plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "/mnt/c/Users/demo/Documents/repos/myownpackage/.venv/lib/python3.6/site-packages/mkdocstrings/plugin.py", line 110, in on_nav
    root_object = self.documenter.get_object_documentation(import_string)
  File "/mnt/c/Users/demo/Documents/repos/myownpackage/.venv/lib/python3.6/site-packages/mkdocstrings/documenter.py", line 305, in get_object_documentation
    root_object = self.get_module_documentation(obj)
  File "/mnt/c/Users/demo/Documents/repos/myownpackage/.venv/lib/python3.6/site-packages/mkdocstrings/documenter.py", line 323, in get_module_documentation
    root_object.add_child(self.get_class_documentation(member, module))
  File "/mnt/c/Users/demo/Documents/repos/myownpackage/.venv/lib/python3.6/site-packages/mkdocstrings/documenter.py", line 362, in get_class_documentation
    source = inspect.getsourcelines(actual_member)
  File "/usr/lib/python3.6/inspect.py", line 955, in getsourcelines
    lines, lnum = findsource(object)
  File "/usr/lib/python3.6/inspect.py", line 786, in findsource
    raise OSError('could not get source code')
OSError: could not get source code
Makefile:64: recipe for target 'docs' failed
make: *** [docs] Error 1
```

**Comment by pawamoy** [comment]
I was able to reproduce. It will now issue a warning instead of failing, but will not retrieve the annotations for the members of your class inheriting from `typing.NamedTuple`. I guess we must implement special handling for such cases, just like for Pydantic models.

**Comment by pawamoy** [comment]
Closing for now. I noticed it works better on Python 3.8 than 3.6/3.7: inspect is able to retrieve source code and signature it was not previsouly able to.
