### ISSUE TITLE
[BUG] 0.5.0

### ISSUE THREAD

**Issue by ofek** [pawamoy/pytkdocs#43]
**Describe the bug**

```
Traceback (most recent call last):
  File "/home/runner/work/integrations-core/integrations-core/.tox/docs/lib/python3.8/site-packages/pytkdocs/cli.py", line 193, in main
    output = json.dumps(process_json(line))
  File "/home/runner/work/integrations-core/integrations-core/.tox/docs/lib/python3.8/site-packages/pytkdocs/cli.py", line 114, in process_json
    return process_config(json.loads(json_input))
  File "/home/runner/work/integrations-core/integrations-core/.tox/docs/lib/python3.8/site-packages/pytkdocs/cli.py", line 91, in process_config
    obj = loader.get_object_documentation(path, members)
  File "/home/runner/work/integrations-core/integrations-core/.tox/docs/lib/python3.8/site-packages/pytkdocs/loader.py", line 232, in get_object_documentation
    root_object = self.get_class_documentation(leaf, members)
  File "/home/runner/work/integrations-core/integrations-core/.tox/docs/lib/python3.8/site-packages/pytkdocs/loader.py", line 333, in get_class_documentation
    merge(attributes_data, get_class_attributes(cls))
  File "/home/runner/work/integrations-core/integrations-core/.tox/docs/lib/python3.8/site-packages/pytkdocs/parsers/attributes.py", line 127, in get_class_attributes
    return combine(get_module_or_class_attributes(nodes[0].body), type_hints)
  File "/home/runner/work/integrations-core/integrations-core/.tox/docs/lib/python3.8/site-packages/pytkdocs/parsers/attributes.py", line 85, in get_module_or_class_attributes
    names = [target.id for target in assignment.targets]
  File "/home/runner/work/integrations-core/integrations-core/.tox/docs/lib/python3.8/site-packages/pytkdocs/parsers/attributes.py", line 85, in <listcomp>
    names = [target.id for target in assignment.targets]
AttributeError: 'Tuple' object has no attribute 'id'
```

**Screenshots**

https://github.com/DataDog/integrations-core/runs/751798110?check_suite_focus=true

**Comment by pawamoy** [comment]
One build breakage, one :clown_face:! Sorry about that! It should be fixed in pytkdocs 0.5.1.

**Comment by ofek** [comment]
Thanks!

**Comment by pawamoy** [comment]
Closing, re-open if needed :slightly_smiling_face:
